name: Windows Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        cargo build --verbose --release --bin rust-gcpv-lynx-export
        cargo build --verbose --release --bin web_export

    - name: Rename Binaries
      run: |
        cd target/release
        mv rust-gcpv-lynx-export.exe gcpv-lynx-generator.exe
        mv web_export.exe gcpv-live.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: sha-${{ github.sha }}
        name: Release ${{ github.sha }}
        files: |
          target/release/gcpv-lynx-generator.exe
          target/release/gcpv-live.exe
        draft: false
        prerelease: false
