name: Windows Release

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Build
      run: |
        cargo build --verbose --release --bin rust-gcpv-lynx-export
        cargo build --verbose --release --bin web_export

    - name: Download mdbtools
      run: |
        curl -L -o mdbtools.zip https://github.com/lsgunth/mdbtools-win/releases/download/v1.0.0/mdbtools-win-x86.zip
        7z x mdbtools.zip -omdbtools

    - name: Prepare Release
      run: |
        mkdir release_pack
        mv target/release/rust-gcpv-lynx-export.exe release_pack/gcpv-lynx-generator.exe
        mv target/release/web_export.exe release_pack/gcpv-live.exe
        copy mdbtools\mdbtools-win-x86\* release_pack\
        cd release_pack
        7z a ../gcpv-windows-release.zip *

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: sha-${{ github.sha }}
        name: Release ${{ github.sha }}
        files: gcpv-windows-release.zip
        draft: false
        prerelease: false
